package ca.uwaterloo.cpami.mahout.matrix.utils;

import java.io.IOException;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.mahout.math.Vector;
import org.apache.mahout.math.hadoop.DistributedRowMatrix;
import org.apache.mahout.math.hadoop.stochasticsvd.SSVDSolver;

import ca.uwaterloo.cpami.css.baselines.HadoopUtils;

/**
 * 
 * Compute the Pseudo Inverse of a matrix A. A should be given as a
 * DistributedRowMatrix. The computation is based on the stochastic SVD.
 * 
 * @see http://en.wikipedia.org/wiki/Moore-Penrose_pseudoinverse#
 *      Singular_value_decomposition_.28SVD.29
 * 
 *      TODO: take a tmp directory as a parameter. TODO: compare to
 *      Lanczos-based computation
 */
public class PseudoInverse {

	private static final String TMP_SSVD_OUTPUT_PATH = "/tmp/inv-ssvd-tmp-path";
	private static final int SSVD_P = 15;

	private static final double JVM_EPS = 1.1e-16;
	private static final String TMP_V_OUT_PATH = "/tmp/v-tmp-out-path";
	private static final String TMP_R_PATH = "/tmp/r-tmp-path";
	private static final String TMP_R_OUT_PATH = "/tmp/r-tmp-out-path";
	private static final String TMP_TTD_PATH = "/tmp/ttd";

	// when applicable
	private int numReducers = 1;

	/**
	 * 
	 * @param numReducers
	 *            : when applicable
	 */
	public void setNumReducers(int numReducers) {
		// this.numReducers = numReducers;
		// TODO for now numReducers is set to 1 since DistributedRowMatrix
		// cannot read from multiple files (files generated from multiple
		// reducers:: V and R in the invert method). It has to be a single file
		// generated by a single
		// reducer.
		this.numReducers = 1;
	}

	public DistributedRowMatrix invert(Path[] matrixPath, int numRows,
			int numCols) throws IOException {
		cleanTmpDirs();
		Configuration conf = new Configuration();
		// ssvd assumes that m >= k+p and n>=k+p
		int k = Math.min(numRows, numCols) - SSVD_P;
		// TODO find a better way (consider matrix size)
		int aBlockRows = 1000;
		SSVDSolver ssvdSolver = new SSVDSolver(conf, matrixPath, new Path(
				TMP_SSVD_OUTPUT_PATH), aBlockRows, k, SSVD_P, numReducers);
		// for a good accuracy
		ssvdSolver.setQ(1);

		ssvdSolver.run();

		Vector sValues = ssvdSolver.getSingularValues();
		Vector sValuesInverted = invertDiagonal(sValues,
				JVM_EPS * Math.max(numRows, numCols) * sValues.get(0));

		Path rPath = new Path(TMP_R_PATH);
		transposeAndTimesDiagonal(
				HadoopUtils.getDataFilePath(ssvdSolver.getUPath()), numRows, k,
				sValuesInverted, TMP_R_PATH);

		DistributedRowMatrix V = new DistributedRowMatrix(
				HadoopUtils.getDataFilePath(ssvdSolver.getVPath()), new Path(
						TMP_V_OUT_PATH), numCols, k);
		V.setConf(conf);

		DistributedRowMatrix R = new DistributedRowMatrix(
				HadoopUtils.getDataFilePath(rPath.toString()), new Path(
						TMP_R_OUT_PATH), k, numRows);
		R.setConf(conf);

		DistributedRowMatrix result = V.transpose().times(R);
		return result;
	}

	/**
	 * S is a diagonal matrix of size numCols x numCols, the values of the
	 * diagonal are given by the vector v. This method computes a matrix R =
	 * S*U'.
	 */
	private void transposeAndTimesDiagonal(Path uPath, int numRows,
			int numCols, Vector v, String outputPath) {
		try {
			new TransposeAndTimesDiagonal()
					.run(v, TMP_TTD_PATH, uPath.toString(), numRows, numCols,
							outputPath, numReducers);
		} catch (Exception e) {
			e.printStackTrace();
			throw new RuntimeException("TransposeAndTimesDiagonal Failed");
		}
	}

	private static void cleanTmpDirs() throws IOException {
		FileSystem fs = FileSystem.get(new Configuration());
		fs.delete(new Path(TMP_SSVD_OUTPUT_PATH), true);
		fs.delete(new Path(TMP_R_OUT_PATH), true);
		fs.delete(new Path(TMP_R_PATH), true);
		fs.delete(new Path(TMP_V_OUT_PATH), true);
		fs.delete(new Path(TMP_TTD_PATH), true);
	}

	/**
	 * 
	 * Each nonzero element is substituted by its reciprocal. An element is
	 * considered nonzero if its value is larger than a certain threshold given
	 * by <i>nonZeroThreshold</i>
	 */
	private static Vector invertDiagonal(Vector v, double nonZeroThreshold) {
		int n = v.size();
		for (int i = 0; i < n; i++) {
			double vi = v.get(i);
			if (vi > nonZeroThreshold)
				v.set(i, 1 / vi);
			else
				v.set(i, 0);
		}
		return v;
	}

}
