package ca.uwaterloo.cpami.mahout.matrix.utils;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileStatus;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.mahout.math.Vector;
import org.apache.mahout.math.hadoop.DistributedRowMatrix;
import org.apache.mahout.math.hadoop.stochasticsvd.SSVDSolver;

import ca.uwaterloo.cpami.css.dataprep.SequenceFileToCSV;

/**
 * 
 * Compute the Pseudo Inverse of a matrix A. A should be given as a
 * DistributedRowMatrix. The computation is based on the stochastic SVD.
 * 
 * @see http://en.wikipedia.org/wiki/Moore-Penrose_pseudoinverse#
 *      Singular_value_decomposition_.28SVD.29
 * 
 *      TODO: take a tmp directory as a parameter. TODO: compare to
 *      Lanczos-based computation
 */
public class PseudoInverse {

	private static final String TMP_SSVD_OUTPUT_PATH = "/tmp/inv-ssvd-tmp-path";
	private static final int SSVD_P = 15;

	private static final double JVM_EPS = 1.1 * 10e-16;
	private static final String TMP_V_OUT_PATH = "/tmp/v-tmp-out-path";
	private static final String TMP_R_PATH = "/tmp/r-tmp-path";
	private static final String TMP_R_OUT_PATH = "/tmp/r-tmp-out-path";
	private static final String TMP_TTD_PATH = "/tmp/ttd";

	// when applicable
	private int numReducers = 1;

	/**
	 * 
	 * @param numReducers
	 *            : when applicable
	 */
	public void setNumReducers(int numReducers) {
		// this.numReducers = numReducers;
		// TODO for now numReducers is set to 1 since DistributedRowMatrix
		// cannot read from multiple files (files generated from multiple
		// reducers:: V and R in the invert method). It has to be a single file
		// generated by a single
		// reducer.
		this.numReducers = 1;
	}

	public DistributedRowMatrix invert(Path[] matrixPath, int numRows,
			int numCols) throws IOException {
		cleanTmpDirs();
		Configuration conf = new Configuration();
		// ssvd assumes that m >= k+p and n>=k+p
		int k = Math.min(numRows, numCols) - SSVD_P;
		// TODO find a better way (consider matrix size)
		int aBlockRows = 1000;
		SSVDSolver ssvdSolver = new SSVDSolver(conf, matrixPath, new Path(
				TMP_SSVD_OUTPUT_PATH), aBlockRows, k, SSVD_P, numReducers);
		// for a good accuracy
		ssvdSolver.setQ(1);

		ssvdSolver.run();

		Vector sValues = ssvdSolver.getSingularValues();
		Vector sValuesInverted = invertDiagonal(sValues,
				JVM_EPS * Math.max(numRows, numCols) * sValues.get(0));

		Path rPath = new Path(TMP_R_PATH);
		transposeAndTimesDiagonal(getDataFilePath(ssvdSolver.getUPath()),
				numRows, k, sValuesInverted, TMP_R_PATH);

		DistributedRowMatrix V = new DistributedRowMatrix(
				getDataFilePath(ssvdSolver.getVPath()),
				new Path(TMP_V_OUT_PATH), numCols, k);
		V.setConf(conf);

		DistributedRowMatrix R = new DistributedRowMatrix(
				getDataFilePath(rPath.toString()), new Path(TMP_R_OUT_PATH), k,
				numRows);
		R.setConf(conf);
		// for now V is transposed before the multiplication. TODO try to
		// omit the extra transpose

		DistributedRowMatrix result = V.transpose().times(R);
		return result;
	}

	private Path getDataFilePath(String outputDirectory) throws IOException {
		FileSystem fs = FileSystem.get(new Configuration());
		FileStatus[] files = fs.listStatus(new Path(outputDirectory));
		for (FileStatus status : files) {
			Path p = status.getPath();
			if (!p.getName().startsWith("_"))
				return p;
		}
		return null;
	}

	/**
	 * S is a diagonal matrix of size numCols x numCols, the values of the
	 * diagonal are given by the vector v. This method computes a matrix R =
	 * S*U'.
	 */
	private void transposeAndTimesDiagonal(Path uPath, int numRows,
			int numCols, Vector v, String outputPath) {
		try {
			new TransposeAndTimesDiagonal()
					.run(v, TMP_TTD_PATH, uPath.toString(), numRows, numCols,
							outputPath, numReducers);
		} catch (Exception e) {
			e.printStackTrace();
			throw new RuntimeException("TransposeAndTimesDiagonal Failed");
		}
	}

	private static void cleanTmpDirs() throws IOException {
		FileSystem fs = FileSystem.get(new Configuration());
		fs.delete(new Path(TMP_SSVD_OUTPUT_PATH), true);
		fs.delete(new Path(TMP_R_OUT_PATH), true);
		fs.delete(new Path(TMP_R_PATH), true);
		fs.delete(new Path(TMP_V_OUT_PATH), true);
		fs.delete(new Path(TMP_TTD_PATH), true);
	}

	/**
	 * 
	 * Each nonzero element is substituted by its reciprocal. An element is
	 * considered nonzero if its value is larger than a certain threshold given
	 * by <i>nonZeroThreshold</i>
	 */
	private static Vector invertDiagonal(Vector v, double nonZeroThreshold) {
		int n = v.size();
		for (int i = 0; i < n; i++) {
			double vi = v.get(i);
			if (vi > nonZeroThreshold)
				v.set(i, 1 / vi);
		}
		return v;
	}

	// test
	public static void main(String[] args) throws IOException {

		DistributedRowMatrix result = new PseudoInverse().invert(
				new Path[] { new Path("/inv/U") }, 99, 99);
		System.out.println(result.getRowPath());
		System.out.println(result.getOutputTempPath());
		SequenceFileToCSV.sequenceFileToCSV(result.getRowPath().toString(),
				"/inv/invmat.csv", ",");

	}

	public static void _main(String[] args) throws IllegalArgumentException,
			SecurityException, IOException, InterruptedException,
			ClassNotFoundException, InstantiationException,
			IllegalAccessException, InvocationTargetException,
			NoSuchMethodException {

		// DistributedRowMatrix mat = new DistributedRowMatrix(new
		// Path("/inv/R"),
		// new Path("/tmp/R"), 99, 99);
		// mat.transpose();
		Path p = new Path("/home/ahmed/_log");
		System.out.println(p.getName().startsWith("_"));
		System.out.println(p.toString());
	}

}
