# Nystrom Approximation
#X is the original data matrix, cols are data instances and rows are features
#m is the number of samples used for the approximation
#kernel is the kernel function generated by kernlab's dots
#k is the used rank for the truncated svd
BasicNystrom <- function(X,m, kernel,k){
  n <- dim(X)[2]
  sampleCols <- sample(n,m)
  partialKernel <- matrix(nrow=n,ncol=m)
  allCols <- 1:n 
  remCols <- allCols[!allCols%in%sampleCols]
  r <- n-m
  for(i in 1:m){
   for(j in 1:i){
       partialKernel[i,j] <- partialKernel[j,i] <- kernel(X[,sampleCols[i]], X[,sampleCols[j]])
    }
   
   for(j in 1:r){
       partialKernel[m+j,i] <- kernel(X[,sampleCols[i]], X[,remCols[j]])
   }
  }
  #truncated svd of samples kernel
  s <- svd(partialKernel[1:m,],nu=0, nv=k)
  Y <- t(partialKernel %*% s$v %*% diag(s$d^-0.5))
  return(Y)
}

Y <- BasicNystrom(t(test$x),100,rbfkernel,10)